### ISSUE TITLE
Fail to build on OSX 10.10

### ISSUE THREAD

**Issue by joneslee85** [imagemin/optipng-bin#60]
`node lib/install.js` does not work due to compilation error. The issue was reported in http://sourceforge.net/p/optipng/bugs/47/ and I could confirm the patch mentioned in that bug description work. In fact, homebrew's version of optipng apply that patch too (https://github.com/Homebrew/homebrew/blob/master/Library/Formula/optipng.rb)

It'd be great if we could apply the patch there.

**Comment by creeperyang** [comment]
Same problem.

```bash
OSX 10.10
Node.JS 0.12.6
NPM 2.11.2
```

**Comment by jhogendorn** [comment]
Same issue.

OSX 10.10.5
Node v5.1.0
NPM 3.3.12

**Comment by shinnn** [comment]
Thanks for the report but I don't want to include any workarounds for http://sourceforge.net/p/optipng/bugs/47/ to this project. Please wait for the optipng author to tackle the problem.

**Comment by jhogendorn** [comment]
For those that come via google, the easiest fix is to install optipng via homebrew and symlink it into the expected location that imagemin errors on :)

**Comment by sebastienbarre** [comment]
It has been 5 months now, and unfortunately this issue is still going on...

**Comment by shinnn** [comment]
Fixed in https://github.com/imagemin/optipng-bin/pull/68.
